# Generated by Django 5.2.8 on 2025-11-10 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_course_is_premium_userenrollment'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, help_text='উত্তরটি কেন সঠিক তার ব্যাখ্যা (ঐচ্ছিক)', null=True),
        ),
    ]
