# Generated by Django 5.2.8 on 2025-11-11 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_question_explanation'),
    ]

    operations = [
        migrations.CreateModel(
            name='MatchingGame',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('order', models.PositiveIntegerField(default=0, help_text='গেমটি ইউনিটে কত নম্বরে দেখাবে')),
                ('unit', models.ForeignKey(help_text='এই গেমটি কোন ইউনিটের অংশ', on_delete=django.db.models.deletion.CASCADE, related_name='matching_games', to='api.unit')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='GamePair',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_one', models.CharField(help_text='কার্ড ১ (যেমন: Apple)', max_length=200)),
                ('item_two', models.CharField(help_text='কার্ড ২ (যেমন: আপেল)', max_length=200)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairs', to='api.matchinggame')),
            ],
        ),
    ]
