# Generated by Django 5.2.8 on 2025-11-11 14:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_matchinggame_gamepair'),
    ]

    operations = [
        migrations.AddField(
            model_name='matchinggame',
            name='game_type',
            field=models.CharField(choices=[('LESSON', 'Lesson Game'), ('UNIT', 'Unit Game')], default='LESSON', max_length=10),
        ),
        migrations.AddField(
            model_name='matchinggame',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text="যদি এটি 'Lesson Game' হয় তবে এখানে লেসনটি লিঙ্ক করুন", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_games', to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='matchinggame',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='গেমটি কত নম্বরে দেখাবে'),
        ),
        migrations.AlterField(
            model_name='matchinggame',
            name='unit',
            field=models.ForeignKey(blank=True, help_text="যদি এটি 'Unit Game' হয় তবে এখানে ইউনিটটি লিঙ্ক করুন", null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_games', to='api.unit'),
        ),
    ]
