# Generated by Django 5.2.8 on 2025-11-12 14:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_learninggroup_groupmembership'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='নোটিশের শিরোনাম', max_length=255)),
                ('body', models.TextField(help_text='নোটিশের মূল বার্তা')),
                ('is_active', models.BooleanField(default=True, help_text='যদি সক্রিয় থাকে, তবে এটি হোমপেজে দেখাবে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Notices',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='প্রমোশনের শিরোনাম (যেমন: 20% Discount)', max_length=200)),
                ('subtitle', models.CharField(blank=True, help_text='ছোট বর্ণনা বা ডেসক্রিপশন', max_length=255, null=True)),
                ('is_active', models.BooleanField(default=True, help_text='যদি সক্রিয় থাকে, তবে এটি হোমপেজে দেখাবে')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='promotions', to='api.course')),
            ],
            options={
                'verbose_name_plural': 'Promotions',
                'ordering': ['-created_at'],
            },
        ),
    ]
