# Generated by Django 5.2.8 on 2025-11-15 17:27

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_notice_promotion'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.AlterModelOptions(
            name='groupmembership',
            options={},
        ),
        migrations.AlterModelOptions(
            name='learninggroup',
            options={},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={},
        ),
        migrations.AlterModelOptions(
            name='promotion',
            options={},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={},
        ),
        migrations.RenameField(
            model_name='userquizattempt',
            old_name='attempted_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='promotion',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='quiz',
            name='order',
        ),
        migrations.RemoveField(
            model_name='userlessonprogress',
            name='completed_at',
        ),
        migrations.AddField(
            model_name='userlessonprogress',
            name='completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='is_correct',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='choice',
            name='text',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='course',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='api.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='gamepair',
            name='item_one',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='gamepair',
            name='item_two',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='is_group_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='groupmembership',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learninggroup',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='admin_groups', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='learninggroup',
            name='courses',
            field=models.ManyToManyField(blank=True, related_name='learning_groups', to='api.course'),
        ),
        migrations.AlterField(
            model_name='learninggroup',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='article_body',
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True, verbose_name='Article'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='youtube_video_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='matchinggame',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_games', to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='matchinggame',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='matchinggame',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='matching_games', to='api.unit'),
        ),
        migrations.AlterField(
            model_name='notice',
            name='body',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='notice',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='notice',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='subtitle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='title',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='points',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='quiz_type',
            field=models.CharField(choices=[('LESSON', 'Lesson Quiz'), ('UNIT', 'Unit Mastery Quiz')], default='LESSON', max_length=10),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quizzes', to='api.unit'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='order',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='enrollments', to='api.course'),
        ),
        migrations.AlterField(
            model_name='userenrollment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_enrollments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='api.lesson'),
        ),
        migrations.AlterField(
            model_name='userlessonprogress',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_progress', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='api.quiz'),
        ),
        migrations.AlterField(
            model_name='userquizattempt',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_attempts', to=settings.AUTH_USER_MODEL),
        ),
    ]
