# Generated by Django 5.2.8 on 2025-11-15 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_category_options_alter_groupmembership_options_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserLessonProgress',
        ),
    ]
